export interface Spot {
  id: string;
  name: string;
  location: string;
  region: string;
  bloomStart: string;
  bloomEnd: string;
  peakStart: string;
  peakEnd: string;
  festival?: string;
  festivalDates?: string;
  tags: string[];
  description: string;
  tip: string;
  accessibility: '상' | '중' | '하';
  crowdLevel: '상' | '중' | '하';
  photoPoint: string;
  imageCredit: string;
}

export const spots: Spot[] = [
  // 제주권
  {
    id: 'jeju-jeonnong',
    name: '전농로 왕벚꽃길',
    location: '제주시',
    region: '제주',
    bloomStart: '3/20',
    bloomEnd: '3/25',
    peakStart: '3/27',
    peakEnd: '4/2',
    tags: ['nature', 'solo', 'couple', 'daytime', 'faraway'],
    description: '국내 첫 벚꽃, 왕벚꽃 원산지. 제주에서 가장 먼저 봄을 만나는 곳으로, 왕벚꽃 나무 터널이 장관을 이룹니다.',
    tip: '평일 오전이 한적해요. 제주공항에서 차로 15분 거리.',
    accessibility: '중',
    crowdLevel: '중',
    photoPoint: '전농로 중앙 도로에서 벚꽃 터널을 배경으로',
    imageCredit: '한국관광공사',
  },
  {
    id: 'jeju-noksanro',
    name: '녹산로 유채꽃+벚꽃길',
    location: '서귀포시',
    region: '제주',
    bloomStart: '3/22',
    bloomEnd: '3/27',
    peakStart: '3/29',
    peakEnd: '4/4',
    tags: ['nature', 'couple', 'family', 'daytime', 'faraway'],
    description: '유채꽃과 벚꽃의 핑크-옐로우 조합. 제주만의 봄 풍경을 한눈에 담을 수 있는 포토로드.',
    tip: '유채꽃은 벚꽃보다 일찍 피니, 3월 말이 두 꽃을 동시에 볼 수 있는 최적기.',
    accessibility: '하',
    crowdLevel: '하',
    photoPoint: '도로 양쪽 유채꽃+벚꽃이 동시에 보이는 지점에서',
    imageCredit: '한국관광공사',
  },
  // 남부권
  {
    id: 'jinhae-yeojwa',
    name: '여좌천 로망스다리',
    location: '창원시 진해구',
    region: '경남',
    bloomStart: '3/22',
    bloomEnd: '3/26',
    peakStart: '3/29',
    peakEnd: '4/5',
    festival: '진해군항제',
    festivalDates: '3/27 - 4/5',
    tags: ['festival', 'couple', 'night', 'overnight'],
    description: '국내 최대 벚꽃 축제, 36만 그루. 여좌천을 따라 이어지는 벚꽃 터널과 로망스다리의 야경은 잊을 수 없는 봄밤.',
    tip: '주말은 인파가 극심해요. 평일 방문 강력 추천! 주차 어려우니 대중교통 이용.',
    accessibility: '중',
    crowdLevel: '상',
    photoPoint: '로망스다리 위에서 양쪽 벚꽃 터널을 배경으로',
    imageCredit: '한국관광공사',
  },
  {
    id: 'jinhae-gyeonghwa',
    name: '경화역 벚꽃 철길',
    location: '창원시 진해구',
    region: '경남',
    bloomStart: '3/22',
    bloomEnd: '3/26',
    peakStart: '3/29',
    peakEnd: '4/5',
    festival: '진해군항제',
    festivalDates: '3/27 - 4/5',
    tags: ['heritage', 'couple', 'daytime', 'overnight'],
    description: '기차+벚꽃 인생샷 명소. 폐역이 된 간이역 플랫폼 위로 쏟아지는 벚꽃이 시간을 멈춘 듯한 풍경.',
    tip: '군항제 기간 셔틀버스 운행. 오전 일찍 방문하면 사람 없는 사진 가능.',
    accessibility: '중',
    crowdLevel: '상',
    photoPoint: '철길 위에서 역 방향으로 벚꽃 터널 촬영',
    imageCredit: '한국관광공사',
  },
  {
    id: 'busan-oncheoncheon',
    name: '온천천 벚꽃길',
    location: '부산 동래구',
    region: '부산',
    bloomStart: '3/23',
    bloomEnd: '3/25',
    peakStart: '3/29',
    peakEnd: '4/2',
    tags: ['urban', 'friends', 'daytime', 'overnight'],
    description: '도심 속 벚꽃 산책로. 부산 시내 한복판을 흐르는 온천천을 따라 이어지는 벚꽃길.',
    tip: '동래역에서 도보 5분. 부산 여행 일정에 가볍게 추가 가능.',
    accessibility: '상',
    crowdLevel: '중',
    photoPoint: '온천천 다리 위에서 양쪽 벚꽃나무 산책로를 배경으로',
    imageCredit: 'Unsplash',
  },
  {
    id: 'gyeongju-daereungwon',
    name: '대릉원 돌담길',
    location: '경주시',
    region: '경북',
    bloomStart: '3/25',
    bloomEnd: '3/28',
    peakStart: '4/1',
    peakEnd: '4/7',
    festival: '경주 벚꽃축제',
    festivalDates: '3/27 - 4/5',
    tags: ['heritage', 'solo', 'couple', 'daytime', 'overnight'],
    description: '천년 고도의 벚꽃, 신라 고분과 돌담길 위로 흐드러지게 피어나는 봄. 역사와 자연이 어우러진 경주만의 감성.',
    tip: '황리단길 카페거리와 연계하면 도보 여행 코스로 최적.',
    accessibility: '중',
    crowdLevel: '중',
    photoPoint: '대릉원 후문 돌담길에서 고분을 배경으로',
    imageCredit: '한국관광공사',
  },
  {
    id: 'gyeongju-bomun',
    name: '보문단지 호수길',
    location: '경주시',
    region: '경북',
    bloomStart: '3/25',
    bloomEnd: '3/28',
    peakStart: '4/1',
    peakEnd: '4/7',
    tags: ['nature', 'family', 'daytime', 'overnight'],
    description: '호수 둘레길 벚꽃 드라이브. 보문호를 감싸는 벚꽃 드라이브 코스는 가족 나들이에 딱.',
    tip: '자전거 대여해서 호수 한 바퀴 도는 것을 추천. 주변 숙소 많아 1박 여행 편리.',
    accessibility: '중',
    crowdLevel: '중',
    photoPoint: '보문호 둘레길에서 호수와 벚꽃을 함께 담는 구도',
    imageCredit: '한국관광공사',
  },
  {
    id: 'daegu-eworld',
    name: '이월드 피크닉 블라썸',
    location: '대구 달서구',
    region: '대구',
    bloomStart: '3/24',
    bloomEnd: '3/28',
    peakStart: '3/31',
    peakEnd: '4/5',
    festival: '이월드 벚꽃축제',
    festivalDates: '3/28 - 4/6',
    tags: ['festival', 'friends', 'family', 'night', 'overnight'],
    description: '국내 최대 야간 벚꽃 축제. 화려한 조명 아래 피어난 벚꽃과 놀이기구의 환상적인 야경.',
    tip: '야간 입장권이 더 저렴해요. 해 질 무렵 입장해서 낮과 밤 벚꽃 모두 즐기기.',
    accessibility: '상',
    crowdLevel: '상',
    photoPoint: '83타워를 배경으로 야간 벚꽃 조명 촬영',
    imageCredit: 'Unsplash',
  },
  {
    id: 'hapcheon-100ri',
    name: '합천 백리벚꽃길',
    location: '합천군',
    region: '경남',
    bloomStart: '3/28',
    bloomEnd: '4/2',
    peakStart: '4/4',
    peakEnd: '4/9',
    tags: ['nature', 'solo', 'couple', 'daytime', 'overnight'],
    description: '한적한 드라이브 코스, 숨은 명소. 100리(약 40km)에 걸친 벚꽃 도로는 아는 사람만 아는 비밀 코스.',
    tip: '차량 필수. 창녕-합천 방면 33번 국도를 따라 드라이브.',
    accessibility: '하',
    crowdLevel: '하',
    photoPoint: '도로 양쪽 벚꽃 터널이 이어지는 직선 구간에서',
    imageCredit: 'Unsplash',
  },
  // 수도권
  {
    id: 'yeouido',
    name: '여의도 윤중로',
    location: '서울 영등포구',
    region: '서울',
    bloomStart: '3/30',
    bloomEnd: '4/2',
    peakStart: '4/6',
    peakEnd: '4/13',
    festival: '여의도 봄꽃축제',
    festivalDates: '4/4 - 4/8',
    tags: ['festival', 'friends', 'both', 'daytrip'],
    description: '서울 대표 벚꽃, 한강과 야경. 윤중로를 가득 메운 벚꽃 터널과 한강의 봄 바람.',
    tip: '여의나루역 1번 출구. 주말은 인파 극심, 평일 야간 방문 추천.',
    accessibility: '상',
    crowdLevel: '상',
    photoPoint: '윤중로 중앙 벚꽃 터널, 또는 한강변에서 벚꽃+63빌딩 구도',
    imageCredit: '한국관광공사',
  },
  {
    id: 'seokchon',
    name: '석촌호수 벚꽃길',
    location: '서울 송파구',
    region: '서울',
    bloomStart: '4/1',
    bloomEnd: '4/3',
    peakStart: '4/7',
    peakEnd: '4/10',
    festival: '석촌호수 벚꽃축제',
    festivalDates: '4/4 - 4/9',
    tags: ['urban', 'couple', 'night', 'daytrip'],
    description: '호수+도시 스카이라인, 야간 조명 강화. 롯데타워를 배경으로 호수를 감싸는 벚꽃의 도시적 아름다움.',
    tip: '잠실역 2번 출구 도보 5분. 야간 조명이 특히 아름다워요.',
    accessibility: '상',
    crowdLevel: '상',
    photoPoint: '석촌호수 서호 다리에서 롯데타워+벚꽃 구도',
    imageCredit: '한국관광공사',
  },
  {
    id: 'namsan',
    name: '남산 둘레길',
    location: '서울 중구/용산구',
    region: '서울',
    bloomStart: '4/1',
    bloomEnd: '4/3',
    peakStart: '4/7',
    peakEnd: '4/10',
    tags: ['nature', 'solo', 'daytime', 'daytrip'],
    description: '도심 속 산책, 서울 전경과 벚꽃. 남산타워를 향해 오르는 길, 벚꽃 사이로 보이는 서울 시내.',
    tip: '남산 순환버스 이용 가능. 체력이 된다면 걸어 올라가는 것이 더 아름다워요.',
    accessibility: '상',
    crowdLevel: '중',
    photoPoint: '남산타워가 보이는 벚꽃 길에서 타워를 배경으로',
    imageCredit: 'Unsplash',
  },
  {
    id: 'palace',
    name: '경복궁/창덕궁',
    location: '서울 종로구',
    region: '서울',
    bloomStart: '4/1',
    bloomEnd: '4/3',
    peakStart: '4/7',
    peakEnd: '4/10',
    tags: ['heritage', 'solo', 'couple', 'daytime', 'daytrip'],
    description: '궁궐+벚꽃 조합, 사진 명소. 한복을 입고 궁궐 담장 아래 벚꽃을 거니는 시간여행.',
    tip: '한복 착용 시 무료 입장! 경복궁 야간개장은 별도 예매 필요.',
    accessibility: '상',
    crowdLevel: '상',
    photoPoint: '경복궁 향원정 또는 창덕궁 후원 입구 벚꽃길',
    imageCredit: '한국관광공사',
  },
  {
    id: 'seoul-forest',
    name: '서울숲',
    location: '서울 성동구',
    region: '서울',
    bloomStart: '4/1',
    bloomEnd: '4/3',
    peakStart: '4/7',
    peakEnd: '4/10',
    tags: ['nature', 'family', 'friends', 'daytime', 'daytrip'],
    description: '넓은 잔디밭, 피크닉 최적. 아이들과 함께 돗자리 펴고 벚꽃 아래 피크닉을 즐기세요.',
    tip: '서울숲역 3번 출구. 돗자리와 간식 챙기면 완벽한 봄 피크닉.',
    accessibility: '상',
    crowdLevel: '중',
    photoPoint: '서울숲 중앙 잔디밭에서 벚꽃나무 아래 피크닉 구도',
    imageCredit: 'Unsplash',
  },
  {
    id: 'suwon',
    name: '수원 화성행궁',
    location: '수원시 팔달구',
    region: '경기',
    bloomStart: '4/3',
    bloomEnd: '4/4',
    peakStart: '4/8',
    peakEnd: '4/13',
    tags: ['heritage', 'family', 'daytime', 'daytrip'],
    description: '유네스코 세계유산+벚꽃. 수원화성 성곽길을 따라 피어난 벚꽃은 역사와 자연의 완벽한 조화.',
    tip: '수원역에서 버스 15분. 화성행궁 야간개장도 추천.',
    accessibility: '상',
    crowdLevel: '중',
    photoPoint: '화성행궁 성곽 위에서 벚꽃과 행궁을 내려다보는 구도',
    imageCredit: '한국관광공사',
  },
  {
    id: 'gwacheon',
    name: '과천 렛츠런파크',
    location: '과천시',
    region: '경기',
    bloomStart: '4/2',
    bloomEnd: '4/4',
    peakStart: '4/8',
    peakEnd: '4/12',
    festival: '야간 벚꽃축제',
    festivalDates: '4/4 - 4/10',
    tags: ['festival', 'family', 'night', 'daytrip'],
    description: '야간 벚꽃+놀이공원 분위기. 낮에는 가족 나들이, 밤에는 조명 아래 환상적인 벚꽃 야경.',
    tip: '경마공원역 2번 출구. 야간 무료 개방 기간을 확인하세요.',
    accessibility: '상',
    crowdLevel: '중',
    photoPoint: '중앙 호수 주변 야간 벚꽃 조명 구간',
    imageCredit: 'Unsplash',
  },
  {
    id: 'uiwang',
    name: '의왕 백운호수',
    location: '의왕시',
    region: '경기',
    bloomStart: '4/3',
    bloomEnd: '4/5',
    peakStart: '4/9',
    peakEnd: '4/13',
    tags: ['nature', 'solo', 'couple', 'daytime', 'daytrip'],
    description: '한적한 호수 산책, 수도권 숨은 명소. 사람 적고 조용한 호수 둘레길, 나만 알고 싶은 벚꽃 산책로.',
    tip: '의왕역에서 버스 이용. 호수 한 바퀴 약 3km, 1시간 산책 코스.',
    accessibility: '중',
    crowdLevel: '하',
    photoPoint: '백운호수 둘레길에서 호수에 비친 벚꽃 반영 촬영',
    imageCredit: 'Unsplash',
  },
  // 강원권
  {
    id: 'gangneung',
    name: '경포호 벚꽃길',
    location: '강릉시',
    region: '강원',
    bloomStart: '4/1',
    bloomEnd: '4/5',
    peakStart: '4/8',
    peakEnd: '4/13',
    festival: '경포 벚꽃축제',
    festivalDates: '4/5 - 4/12',
    tags: ['nature', 'couple', 'daytime', 'overnight'],
    description: '바다+호수+벚꽃 트리플 조합. 경포호를 감싸는 벚꽃길에서 바다까지 한 걸음.',
    tip: '강릉 KTX로 서울에서 2시간. 경포해변 일출+벚꽃 조합 추천.',
    accessibility: '중',
    crowdLevel: '중',
    photoPoint: '경포호 둘레길에서 호수와 벚꽃, 먼 바다까지 담는 구도',
    imageCredit: '한국관광공사',
  },
  {
    id: 'yangpyeong',
    name: '양평 두물머리',
    location: '양평군',
    region: '경기',
    bloomStart: '4/7',
    bloomEnd: '4/10',
    peakStart: '4/13',
    peakEnd: '4/17',
    tags: ['nature', 'solo', 'couple', 'daytime', 'overnight'],
    description: '서울 벚꽃 놓쳤을 때 대안, 강변 풍경. 두물머리의 고요한 강변에서 늦은 봄을 만끽.',
    tip: '서울 벚꽃이 끝난 후 1주일 뒤가 적기. 아침 물안개+벚꽃 조합이 환상적.',
    accessibility: '하',
    crowdLevel: '하',
    photoPoint: '두물머리 느티나무와 강변 벚꽃을 함께 담는 새벽 구도',
    imageCredit: 'Unsplash',
  },
  {
    id: 'gapyeong',
    name: '가평 에덴벚꽃길',
    location: '가평군',
    region: '경기',
    bloomStart: '4/7',
    bloomEnd: '4/10',
    peakStart: '4/13',
    peakEnd: '4/17',
    festival: '가평 벚꽃축제',
    festivalDates: '4/10 - 4/15',
    tags: ['nature', 'family', 'daytime', 'overnight'],
    description: '서울 근교 1박, 늦은 벚꽃. 가평의 자연 속에서 여유롭게 즐기는 늦봄 벚꽃 여행.',
    tip: '가평역에서 도보 가능. 자라섬과 연계 코스 추천.',
    accessibility: '중',
    crowdLevel: '하',
    photoPoint: '에덴벚꽃길 가로수 터널에서 길을 따라 촬영',
    imageCredit: 'Unsplash',
  },
];

export interface QuizQuestion {
  id: string;
  question: string;
  options: { label: string; tag: string }[];
}

export const questions: QuizQuestion[] = [
  {
    id: 'companion',
    question: '누구와 함께 가시나요?',
    options: [
      { label: '혼자 여유롭게', tag: 'solo' },
      { label: '연인과 로맨틱하게', tag: 'couple' },
      { label: '친구들과 신나게', tag: 'friends' },
      { label: '가족과 함께', tag: 'family' },
    ],
  },
  {
    id: 'mood',
    question: '어떤 분위기를 원하시나요?',
    options: [
      { label: '도심 속 산책', tag: 'urban' },
      { label: '자연 속 힐링', tag: 'nature' },
      { label: '축제 분위기', tag: 'festival' },
      { label: '역사적 풍경', tag: 'heritage' },
    ],
  },
  {
    id: 'time',
    question: '벚꽃은 언제 보고 싶으세요?',
    options: [
      { label: '낮의 화사한 벚꽃', tag: 'daytime' },
      { label: '밤의 몽환적인 야간 벚꽃', tag: 'night' },
      { label: '둘 다 즐기고 싶어요', tag: 'both' },
    ],
  },
  {
    id: 'style',
    question: '여행 스타일은?',
    options: [
      { label: '당일치기 (수도권 중심)', tag: 'daytrip' },
      { label: '1박 이상 여행 OK', tag: 'overnight' },
      { label: '멀리 떠나고 싶어요', tag: 'faraway' },
    ],
  },
];

// Matching weights: Q2(mood) > Q4(style) > Q1(companion) > Q3(time)
const tagWeights: Record<string, number> = {
  // Q2 mood - highest priority
  urban: 4,
  nature: 4,
  festival: 4,
  heritage: 4,
  // Q4 style
  daytrip: 3,
  overnight: 3,
  faraway: 3,
  // Q1 companion
  solo: 2,
  couple: 2,
  friends: 2,
  family: 2,
  // Q3 time
  daytime: 1,
  night: 1,
  both: 1,
};

export function matchSpots(selectedTags: string[]): Spot[] {
  const scored = spots.map((spot) => {
    let score = 0;
    for (const tag of selectedTags) {
      const weight = tagWeights[tag] || 1;
      if (spot.tags.includes(tag)) {
        score += weight;
      }
      // 'both' matches both daytime and night
      if (tag === 'both' && (spot.tags.includes('daytime') || spot.tags.includes('night'))) {
        score += weight;
      }
    }
    return { spot, score };
  });

  scored.sort((a, b) => b.score - a.score);

  // Return top 3 unique spots
  return scored.slice(0, 3).map((s) => s.spot);
}
